services:
  postgres:
    image: postgres:16
    container_name: keepintouch-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "keepintouch"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passer123"
    ports:
      - "5432:5432"
    volumes:
      - keepintouch_pgdata:/var/lib/postgresql/data

volumes:
  keepintouch_pgdata: